<%
distrib, infos    = ENV.fetch('DISTRIB', 'debian:stretch/9').split(':')
codename, version = infos.split('/')
%>
---
driver:
  name: docker
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  formula: ufw

  # Install Salt from official repositories
  salt_install: apt
  salt_version: latest
  salt_apt_repo: https://repo.saltstack.com/apt/<%= distrib %>/<%= version %>/amd64
  salt_apt_repo_key: https://repo.saltstack.com/apt/<%= distrib %>/<%= version %>/amd64/latest/SALTSTACK-GPG-KEY.pub

  # Don't install Chef
  require_chef: false

  # Configure Salt
  state_top:
    base:
      '*':
        - ufw

  pillars:
    top.sls:
      base:
        '*':
          - ufw
    ufw.sls:
      ufw:
        enabled: True
        settings:
          loglevel: 'low'
        services:
          '22':
            protocol: tcp
            comment: Allow SSH

platforms:
  - name: <%= distrib %>-<%= codename %>
    driver_config:
      image: "<%= distrib %>:<%= codename %>"
      platform: <%= distrib %>
      provision_command:
        - apt-get update && apt-get install -y locales
        - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        - locale-gen en_US.UTF-8
      run_command: /lib/systemd/systemd

verifier:
  name: inspec
  reporter: progress

suites:
  - name: ufw

